# -*- coding: utf-8 -*-
"""Train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fafL80nqzT9HWu1Zj6Z2EcfKH-5ax95X
"""

# generate_models.py
# Trains 6 classification models on the Breast Cancer Wisconsin (Diagnostic) dataset
# and saves them to model/*.pkl (Joblib format with .pkl extension)

import os
from pathlib import Path
import joblib
import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

MODEL_DIR = Path("model")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

def build_models():
    """Return a dict of model_name -> sklearn/xgboost estimator (or Pipeline)."""
    return {
        "logistic_regression.pkl": Pipeline([
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(max_iter=500, solver="lbfgs"))
        ]),
        "decision_tree.pkl": DecisionTreeClassifier(random_state=42),
        "knn.pkl": Pipeline([
            ("scaler", StandardScaler()),
            ("clf", KNeighborsClassifier(n_neighbors=7))
        ]),
        "naive_bayes.pkl": Pipeline([
            # Scaling not required for NB, but kept for parity with app/metrics
            ("scaler", StandardScaler(with_mean=False)),
            ("clf", GaussianNB())
        ]),
        "random_forest.pkl": RandomForestClassifier(
            n_estimators=300, random_state=42
        ),
        "xgboost.pkl": XGBClassifier(
            n_estimators=400,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.9,
            colsample_bytree=0.9,
            reg_lambda=1.0,
            random_state=42,
            eval_metric="logloss",
            n_jobs=4
        )
    }

def main():
    # Load dataset
    ds = load_breast_cancer()
    X = pd.DataFrame(ds.data, columns=ds.feature_names)
    y = pd.Series(ds.target, name="target")

    models = build_models()
    for filename, model in models.items():
        model.fit(X, y)  # Fit on full data for final artifacts
        path = MODEL_DIR / filename
        joblib.dump(model, path)
        print(f"Saved: {path}")

    # Optional: save a small sample test CSV for app users
    sample = X.sample(10, random_state=42)
    Path("data").mkdir(parents=True, exist_ok=True)
    sample.to_csv("data/sample_test.csv", index=False)
    print("Wrote: data/sample_test.csv")

if __name__ == "__main__":
    main()